### ISSUE TITLE
bin/cbd vendor file

### ISSUE THREAD

**Issue by schwabe93** [lssjbrolli/android_device_samsung_klimtlte#1]
Hi i am again with the vendor files, is see at your repo that the extracted files were changed, so i extract again from my device/eusphros cm12/ and other T705 rom. But i dont find that : bin/cbd .
so where do you find it.
Sorry for my english is not so good i am from germany

**Comment by lssjbrolli** [comment]
should be on eousphoros rom, try to run it from shell, if its running you can use 'which cbd' and you will get the path.

**Comment by schwabe93** [comment]
nope, dont find it with cbd or other search programs, can you please share  this file? please

**Comment by lssjbrolli** [comment]
https://www.dropbox.com/s/i6cira07x23g2w4/cbd?dl=0

**Comment by schwabe93** [comment]
me again, where you get allt the vendor files i downloaded many roms from sammobile, cm12-1 from eosphoros but like camera.universal520 or so.
So where do you get these file.

Thanks :)

**Comment by lssjbrolli** [comment]
which files are you looking for?

**Comment by lssjbrolli** [comment]
on stock rom camera.universal520.so is in /system/lib/hw
but on aosp based roms camera.universal520.so is a wrapper(built from source) that loads camera.vendor.universal520.so which is camera.universal520.so from stock rom.

**Comment by schwabe93** [comment]
ok it works, i downlaoded the stock rom again , building now to test if its booting up

**Comment by schwabe93** [comment]
With New vendor files my Rom doesnt Boot up, does your cm booting up with the vendor files

**Comment by lssjbrolli** [comment]
at the moment i stoped all dev, not enough time :(, but last time i built it it didn't work either with the kernel from klimtwifi, but it works with kernel source you get from http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=t705

**Comment by lssjbrolli** [comment]
get SM-T705_LL_Opensource.zip from there and it should work with stock blobs

**Comment by schwabe93** [comment]
Ok thanks ill try it with the kernel source from samsung

**Comment by schwabe93** [comment]
Hi i See you workin now again on the Device, dies the ril now work?

**Comment by schwabe93** [comment]
And do i need also build Samsung IPC from your repositor, and the Hardware Samsung ril, ?

**Comment by lssjbrolli** [comment]
ril not working at the moment, i'm trying to port Samsung IPC and Samsung ril from replicant project but everything is in VERY early stages.

**Comment by schwabe93** [comment]
OK if you need help to testing or so im helping you out, also on my Server builds are done in 35 minutes, so if you need help im here

**Comment by schwabe93** [comment]
How its the process going?

**Comment by lssjbrolli** [comment]
Pretty good, modem boots up without cbd but I still have to work on
managing ril requests.

**Comment by schwabe93** [comment]
Hi me again:) im still interesting how its going on?

**Comment by lssjbrolli** [comment]
not so well, i had very little free time this last 2 weeks :(
